name: Feathers And Cogs
favicon: null
layout_spectrum: 0.7581116417422891
typography_spectrum: 0.8159451927058399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#bb9d6b'
    - '#382914'
    - '#68502c'
    - '#a48654'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
